#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Profile:
    name: str
    sigma_n0: float
    dyn_forget_gain: float
    phi: float
    rho: float
    min_weight: float
    max_dscore: float
    max_free_ratio: float
    use_zc: bool
    zc_phi_gate: float
    zc_max_offset: float
    cons_enable: bool
    cons_neighbors: int
    cons_cos: float
    cons_phi_diff: float
    snef_enable: bool
    snef_block: int
    snef_qd: float
    snef_md: float
    snef_qf: float
    snef_mf: float
    snef_qphi: float
    snef_mphi: float
    snef_min_keep: int
    snef_keep_ratio: float
    snef_min_candidates: int
    snef_anchor_rho_q: float
    snef_anchor_dscore_q: float
    snef_anchor_min: int
    two_stage_enable: bool
    two_stage_geom_margin: float
    two_stage_dyn_dscore_q: float
    two_stage_dyn_free_q: float
    two_stage_dyn_rho_q: float = 0.40
    two_stage_dyn_rho_margin: float = 0.0
    two_stage_dyn_require_low_rho: bool = True
    # LZCD: local zero-crossing debias.
    lzcd_enable: bool = False
    lzcd_interval: int = 2
    lzcd_radius_cells: int = 1
    lzcd_min_neighbors: int = 6
    lzcd_min_phi_w: float = 0.40
    lzcd_min_rho: float = 0.05
    lzcd_max_dscore: float = 0.85
    lzcd_neighbor_phi_gate: float = 0.25
    lzcd_normal_cos_min: float = 0.45
    lzcd_bias_alpha: float = 0.18
    lzcd_correction_gain: float = 0.35
    lzcd_max_bias: float = 0.06
    lzcd_max_step: float = 0.02
    lzcd_trim_quantile: float = 0.75
    lzcd_use_geo_channel: bool = True
    surface_lzcd_apply_in_extraction: bool = False
    surface_lzcd_bias_scale: float = 1.0
    # STCG: spatio-temporal contradiction gating.
    stcg_enable: bool = False
    stcg_alpha: float = 0.12
    stcg_conflict_weight: float = 0.60
    stcg_residual_weight: float = 0.25
    stcg_osc_weight: float = 0.15
    stcg_free_ratio_ref: float = 0.90
    stcg_on_thresh: float = 0.58
    stcg_off_thresh: float = 0.42
    surface_stcg_enable: bool = False
    surface_stcg_min_score: float = 0.35
    surface_stcg_rho_ref: float = 1.8
    surface_stcg_free_shrink: float = 0.45
    surface_stcg_phi_shrink: float = 0.25
    surface_stcg_dscore_shrink: float = 0.30
    surface_stcg_weight_gain: float = 0.50
    surface_stcg_static_protect: float = 0.70
    surface_use_phi_geo_channel: bool = False
    # Associator heteroscedastic noise.
    assoc_hetero_enable: bool = False
    assoc_hetero_inc_ref_cos: float = 0.65
    assoc_hetero_depth_ref_m: float = 2.5
    assoc_hetero_normal_ref: float = 0.20
    assoc_hetero_k_inc: float = 0.45
    assoc_hetero_k_depth: float = 0.12
    assoc_hetero_k_normal: float = 0.55
    assoc_hetero_good_cos: float = 0.90
    assoc_hetero_good_bonus: float = 0.20
    assoc_hetero_sigma_d_min_scale: float = 0.75
    assoc_hetero_sigma_d_max_scale: float = 1.75
    assoc_hetero_sigma_n_min_scale: float = 0.70
    assoc_hetero_sigma_n_max_scale: float = 2.20


PROFILES: List[Profile] = [
    Profile(
        name="baseline_relaxed",
        sigma_n0=0.26,
        dyn_forget_gain=0.00,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.05,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.00,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_calib_a",
        sigma_n0=0.24,
        dyn_forget_gain=0.03,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.00,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_calib_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.05,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.00,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_calib_c",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.00,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_biasfix_a",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.03,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_biasfix_b",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_biasfix_c",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_soft_cover",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.95,
        snef_md=0.08,
        snef_qf=0.97,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.02,
        snef_min_keep=24,
        snef_keep_ratio=0.75,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.85,
        snef_anchor_dscore_q=0.45,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.10,
        two_stage_dyn_dscore_q=0.85,
        two_stage_dyn_free_q=0.85,
    ),
    Profile(
        name="snef_soft_dynamic",
        sigma_n0=0.20,
        dyn_forget_gain=0.08,
        phi=0.80,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.06,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.90,
        snef_md=0.06,
        snef_qf=0.93,
        snef_mf=0.08,
        snef_qphi=0.98,
        snef_mphi=0.02,
        snef_min_keep=20,
        snef_keep_ratio=0.60,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.88,
        snef_anchor_dscore_q=0.40,
        snef_anchor_min=4,
        two_stage_enable=True,
        two_stage_geom_margin=0.08,
        two_stage_dyn_dscore_q=0.80,
        two_stage_dyn_free_q=0.80,
    ),
    Profile(
        name="snef_mild",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.50,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.06,
        cons_enable=True,
        cons_neighbors=3,
        cons_cos=0.54,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.88,
        snef_md=0.06,
        snef_qf=0.92,
        snef_mf=0.10,
        snef_qphi=0.92,
        snef_mphi=0.04,
        snef_min_keep=20,
        snef_keep_ratio=0.55,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.88,
        snef_anchor_dscore_q=0.35,
        snef_anchor_min=4,
        two_stage_enable=True,
        two_stage_geom_margin=0.05,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_balanced",
        sigma_n0=0.22,
        dyn_forget_gain=0.05,
        phi=0.40,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.10,
        zc_max_offset=0.05,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.56,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.84,
        snef_md=0.05,
        snef_qf=0.90,
        snef_mf=0.10,
        snef_qphi=0.86,
        snef_mphi=0.03,
        snef_min_keep=18,
        snef_keep_ratio=0.45,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.30,
        snef_anchor_min=3,
        two_stage_enable=True,
        two_stage_geom_margin=0.04,
        two_stage_dyn_dscore_q=0.72,
        two_stage_dyn_free_q=0.72,
    ),
    Profile(
        name="snef_strict",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.16,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.035,
        zc_max_offset=0.04,
        cons_enable=True,
        cons_neighbors=6,
        cons_cos=0.68,
        cons_phi_diff=0.03,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.65,
        snef_md=0.02,
        snef_qf=0.78,
        snef_mf=0.05,
        snef_qphi=0.45,
        snef_mphi=0.015,
        snef_min_keep=14,
        snef_keep_ratio=0.45,
        snef_min_candidates=9,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=3,
        two_stage_enable=True,
        two_stage_geom_margin=0.04,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_ghost_first",
        sigma_n0=0.24,
        dyn_forget_gain=0.06,
        phi=0.28,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.045,
        zc_max_offset=0.05,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.60,
        cons_phi_diff=0.035,
        snef_enable=True,
        snef_block=6,
        snef_qd=0.58,
        snef_md=0.02,
        snef_qf=0.75,
        snef_mf=0.04,
        snef_qphi=0.40,
        snef_mphi=0.01,
        snef_min_keep=12,
        snef_keep_ratio=0.40,
        snef_min_candidates=8,
        snef_anchor_rho_q=0.88,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=3,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.68,
        two_stage_dyn_free_q=0.68,
    ),
    Profile(
        name="baseline_joint_a",
        sigma_n0=0.26,
        dyn_forget_gain=0.02,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_b",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.14,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_c",
        sigma_n0=0.22,
        dyn_forget_gain=0.06,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_d",
        sigma_n0=0.24,
        dyn_forget_gain=0.08,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.18,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_e",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.60,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.10,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_f",
        sigma_n0=0.26,
        dyn_forget_gain=0.05,
        phi=0.60,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_g",
        sigma_n0=0.20,
        dyn_forget_gain=0.10,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.85,
        max_free_ratio=1.0,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h",
        sigma_n0=0.22,
        dyn_forget_gain=0.10,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.80,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_i",
        sigma_n0=0.24,
        dyn_forget_gain=0.08,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.78,
        max_free_ratio=0.80,
        use_zc=True,
        zc_phi_gate=0.18,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_j",
        sigma_n0=0.20,
        dyn_forget_gain=0.06,
        phi=0.68,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.82,
        max_free_ratio=0.75,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_k",
        sigma_n0=0.26,
        dyn_forget_gain=0.04,
        phi=0.76,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.90,
        max_free_ratio=0.95,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_stage2_joint_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.08,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.82,
        max_free_ratio=0.85,
        use_zc=True,
        zc_phi_gate=0.18,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=3,
        cons_cos=0.52,
        cons_phi_diff=0.05,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.70,
        snef_md=0.03,
        snef_qf=0.78,
        snef_mf=0.06,
        snef_qphi=0.90,
        snef_mphi=0.02,
        snef_min_keep=20,
        snef_keep_ratio=0.45,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.30,
        snef_anchor_min=4,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.65,
        two_stage_dyn_free_q=0.65,
    ),
    Profile(
        name="snef_stage2_joint_b",
        sigma_n0=0.24,
        dyn_forget_gain=0.06,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.88,
        max_free_ratio=0.95,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=3,
        cons_cos=0.54,
        cons_phi_diff=0.05,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.74,
        snef_md=0.04,
        snef_qf=0.82,
        snef_mf=0.08,
        snef_qphi=0.92,
        snef_mphi=0.02,
        snef_min_keep=20,
        snef_keep_ratio=0.55,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.32,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_stage2_joint_c",
        sigma_n0=0.20,
        dyn_forget_gain=0.10,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.75,
        max_free_ratio=0.75,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.56,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.62,
        snef_md=0.02,
        snef_qf=0.72,
        snef_mf=0.05,
        snef_qphi=0.86,
        snef_mphi=0.02,
        snef_min_keep=18,
        snef_keep_ratio=0.40,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.88,
        snef_anchor_dscore_q=0.28,
        snef_anchor_min=3,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.60,
        two_stage_dyn_free_q=0.60,
    ),
    Profile(
        name="snef_stage2_rho_gate_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.08,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.84,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.18,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=3,
        cons_cos=0.54,
        cons_phi_diff=0.05,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.66,
        snef_md=0.03,
        snef_qf=0.76,
        snef_mf=0.06,
        snef_qphi=0.90,
        snef_mphi=0.02,
        snef_min_keep=20,
        snef_keep_ratio=0.55,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.92,
        snef_anchor_dscore_q=0.32,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.62,
        two_stage_dyn_free_q=0.62,
        two_stage_dyn_rho_q=0.38,
        two_stage_dyn_rho_margin=0.04,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="snef_stage2_rho_gate_b",
        sigma_n0=0.20,
        dyn_forget_gain=0.10,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.80,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.60,
        snef_md=0.02,
        snef_qf=0.72,
        snef_mf=0.05,
        snef_qphi=0.88,
        snef_mphi=0.02,
        snef_min_keep=18,
        snef_keep_ratio=0.50,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.92,
        snef_anchor_dscore_q=0.30,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.58,
        two_stage_dyn_free_q=0.58,
        two_stage_dyn_rho_q=0.35,
        two_stage_dyn_rho_margin=0.03,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="snef_stage2_rho_gate_c",
        sigma_n0=0.24,
        dyn_forget_gain=0.06,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.88,
        max_free_ratio=0.95,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=3,
        cons_cos=0.52,
        cons_phi_diff=0.05,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.70,
        snef_md=0.04,
        snef_qf=0.80,
        snef_mf=0.08,
        snef_qphi=0.92,
        snef_mphi=0.02,
        snef_min_keep=22,
        snef_keep_ratio=0.60,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.34,
        snef_anchor_min=8,
        two_stage_enable=True,
        two_stage_geom_margin=0.03,
        two_stage_dyn_dscore_q=0.66,
        two_stage_dyn_free_q=0.66,
        two_stage_dyn_rho_q=0.42,
        two_stage_dyn_rho_margin=0.05,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="snef_precision_guarded_a",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.95,
        snef_md=0.07,
        snef_qf=0.97,
        snef_mf=0.08,
        snef_qphi=1.00,
        snef_mphi=0.02,
        snef_min_keep=24,
        snef_keep_ratio=0.60,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.82,
        snef_anchor_dscore_q=0.40,
        snef_anchor_min=8,
        two_stage_enable=True,
        two_stage_geom_margin=0.08,
        two_stage_dyn_dscore_q=0.88,
        two_stage_dyn_free_q=0.88,
    ),
    Profile(
        name="snef_precision_guarded_b",
        sigma_n0=0.24,
        dyn_forget_gain=0.04,
        phi=0.70,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.10,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.92,
        snef_md=0.05,
        snef_qf=0.95,
        snef_mf=0.06,
        snef_qphi=0.98,
        snef_mphi=0.02,
        snef_min_keep=24,
        snef_keep_ratio=0.50,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.85,
        snef_anchor_dscore_q=0.38,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.06,
        two_stage_dyn_dscore_q=0.85,
        two_stage_dyn_free_q=0.85,
    ),
    Profile(
        name="baseline_joint_h_tune_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.14,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.72,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_tune_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.16,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.70,
        max_free_ratio=0.78,
        use_zc=True,
        zc_phi_gate=0.24,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_tune_c",
        sigma_n0=0.24,
        dyn_forget_gain=0.12,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.74,
        max_free_ratio=0.85,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_stage2_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.20,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.78,
        max_free_ratio=0.88,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=5,
        cons_cos=0.58,
        cons_phi_diff=0.035,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=True,
        two_stage_geom_margin=0.02,
        two_stage_dyn_dscore_q=0.62,
        two_stage_dyn_free_q=0.65,
        two_stage_dyn_rho_q=0.55,
        two_stage_dyn_rho_margin=0.02,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="baseline_joint_h_stage2_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.24,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.76,
        max_free_ratio=0.84,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.60,
        cons_phi_diff=0.03,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=True,
        two_stage_geom_margin=0.015,
        two_stage_dyn_dscore_q=0.60,
        two_stage_dyn_free_q=0.62,
        two_stage_dyn_rho_q=0.60,
        two_stage_dyn_rho_margin=0.03,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="baseline_joint_h_stage2_c",
        sigma_n0=0.20,
        dyn_forget_gain=0.18,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.74,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.57,
        cons_phi_diff=0.035,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=True,
        two_stage_geom_margin=0.02,
        two_stage_dyn_dscore_q=0.64,
        two_stage_dyn_free_q=0.66,
        two_stage_dyn_rho_q=0.55,
        two_stage_dyn_rho_margin=0.02,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="baseline_joint_h_stage2_d",
        sigma_n0=0.22,
        dyn_forget_gain=0.28,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.72,
        max_free_ratio=0.80,
        use_zc=True,
        zc_phi_gate=0.24,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=True,
        two_stage_geom_margin=0.01,
        two_stage_dyn_dscore_q=0.55,
        two_stage_dyn_free_q=0.58,
        two_stage_dyn_rho_q=0.60,
        two_stage_dyn_rho_margin=0.04,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="baseline_joint_h_stage2_e",
        sigma_n0=0.22,
        dyn_forget_gain=0.24,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.76,
        max_free_ratio=0.86,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=True,
        cons_neighbors=4,
        cons_cos=0.58,
        cons_phi_diff=0.035,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=True,
        two_stage_geom_margin=0.02,
        two_stage_dyn_dscore_q=0.62,
        two_stage_dyn_free_q=0.64,
        two_stage_dyn_rho_q=0.58,
        two_stage_dyn_rho_margin=0.02,
        two_stage_dyn_require_low_rho=False,
    ),
    Profile(
        name="baseline_joint_h_dyn03",
        sigma_n0=0.22,
        dyn_forget_gain=0.30,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.80,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_dyn05",
        sigma_n0=0.22,
        dyn_forget_gain=0.50,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.80,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_dyn08",
        sigma_n0=0.22,
        dyn_forget_gain=0.80,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.80,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_dyn03_tight",
        sigma_n0=0.22,
        dyn_forget_gain=0.30,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.74,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_dyn05_tight",
        sigma_n0=0.22,
        dyn_forget_gain=0.50,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.74,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="baseline_joint_h_dyn08_tight",
        sigma_n0=0.22,
        dyn_forget_gain=0.80,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.74,
        max_free_ratio=0.82,
        use_zc=True,
        zc_phi_gate=0.22,
        zc_max_offset=0.015,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
    ),
    Profile(
        name="snef_local_dynblock_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.50,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.90,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.78,
        snef_md=0.03,
        snef_qf=0.80,
        snef_mf=0.05,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.55,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.92,
        snef_anchor_dscore_q=0.30,
        snef_anchor_min=6,
        two_stage_enable=True,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.55,
        two_stage_dyn_free_q=0.60,
        two_stage_dyn_rho_q=0.55,
        two_stage_dyn_rho_margin=0.0,
        two_stage_dyn_require_low_rho=False,
    ),
    Profile(
        name="snef_local_dynblock_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.80,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.95,
        max_free_ratio=0.92,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.72,
        snef_md=0.02,
        snef_qf=0.75,
        snef_mf=0.02,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=14,
        snef_keep_ratio=0.45,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.35,
        snef_anchor_min=4,
        two_stage_enable=True,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.50,
        two_stage_dyn_free_q=0.55,
        two_stage_dyn_rho_q=0.65,
        two_stage_dyn_rho_margin=0.0,
        two_stage_dyn_require_low_rho=False,
    ),
    Profile(
        name="snef_local_dynblock_c",
        sigma_n0=0.22,
        dyn_forget_gain=0.30,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=0.88,
        max_free_ratio=0.90,
        use_zc=True,
        zc_phi_gate=0.20,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=True,
        snef_block=8,
        snef_qd=0.82,
        snef_md=0.04,
        snef_qf=0.84,
        snef_mf=0.06,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=18,
        snef_keep_ratio=0.65,
        snef_min_candidates=12,
        snef_anchor_rho_q=0.93,
        snef_anchor_dscore_q=0.28,
        snef_anchor_min=8,
        two_stage_enable=True,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.60,
        two_stage_dyn_free_q=0.65,
        two_stage_dyn_rho_q=0.55,
        two_stage_dyn_rho_margin=0.0,
        two_stage_dyn_require_low_rho=True,
    ),
    Profile(
        name="lzcd_only_a",
        sigma_n0=0.24,
        dyn_forget_gain=0.02,
        phi=0.78,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.14,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=6,
        lzcd_neighbor_phi_gate=0.28,
        lzcd_normal_cos_min=0.40,
        lzcd_bias_alpha=0.22,
        lzcd_correction_gain=0.45,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
    ),
    Profile(
        name="lzcd_only_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.03,
        phi=0.76,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.22,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.28,
        lzcd_correction_gain=0.52,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.1,
    ),
    Profile(
        name="lzcd_stcg_balanced",
        sigma_n0=0.22,
        dyn_forget_gain=0.03,
        phi=0.76,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.16,
        stcg_conflict_weight=0.62,
        stcg_residual_weight=0.24,
        stcg_osc_weight=0.14,
        stcg_free_ratio_ref=0.85,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.32,
        surface_stcg_rho_ref=1.6,
        surface_stcg_free_shrink=0.26,
        surface_stcg_phi_shrink=0.10,
        surface_stcg_dscore_shrink=0.10,
        surface_stcg_weight_gain=0.20,
        surface_stcg_static_protect=0.82,
    ),
    Profile(
        name="lzcd_stcg_ghost35",
        sigma_n0=0.22,
        dyn_forget_gain=0.04,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.66,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.80,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.28,
        surface_stcg_rho_ref=1.6,
        surface_stcg_free_shrink=0.40,
        surface_stcg_phi_shrink=0.15,
        surface_stcg_dscore_shrink=0.20,
        surface_stcg_weight_gain=0.35,
        surface_stcg_static_protect=0.80,
    ),
    Profile(
        name="lzcd_stcg_hetero_a",
        sigma_n0=0.22,
        dyn_forget_gain=0.04,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.66,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.80,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.28,
        surface_stcg_rho_ref=1.6,
        surface_stcg_free_shrink=0.40,
        surface_stcg_phi_shrink=0.15,
        surface_stcg_dscore_shrink=0.20,
        surface_stcg_weight_gain=0.35,
        surface_stcg_static_protect=0.80,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.68,
        assoc_hetero_depth_ref_m=2.2,
        assoc_hetero_normal_ref=0.18,
        assoc_hetero_k_inc=0.50,
        assoc_hetero_k_depth=0.16,
        assoc_hetero_k_normal=0.60,
        assoc_hetero_good_cos=0.92,
        assoc_hetero_good_bonus=0.20,
        assoc_hetero_sigma_d_min_scale=0.72,
        assoc_hetero_sigma_d_max_scale=1.70,
        assoc_hetero_sigma_n_min_scale=0.68,
        assoc_hetero_sigma_n_max_scale=2.10,
    ),
    Profile(
        name="lzcd_stcg_hetero_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.04,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.66,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.80,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.28,
        surface_stcg_rho_ref=1.6,
        surface_stcg_free_shrink=0.40,
        surface_stcg_phi_shrink=0.15,
        surface_stcg_dscore_shrink=0.20,
        surface_stcg_weight_gain=0.35,
        surface_stcg_static_protect=0.80,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.62,
        assoc_hetero_depth_ref_m=2.0,
        assoc_hetero_normal_ref=0.16,
        assoc_hetero_k_inc=0.62,
        assoc_hetero_k_depth=0.18,
        assoc_hetero_k_normal=0.68,
        assoc_hetero_good_cos=0.90,
        assoc_hetero_good_bonus=0.18,
        assoc_hetero_sigma_d_min_scale=0.70,
        assoc_hetero_sigma_d_max_scale=1.65,
        assoc_hetero_sigma_n_min_scale=0.65,
        assoc_hetero_sigma_n_max_scale=2.00,
    ),
    Profile(
        name="lzcd_stcg_hetero_c",
        sigma_n0=0.22,
        dyn_forget_gain=0.04,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.16,
        zc_max_offset=0.02,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.0,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.45,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.66,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.80,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.28,
        surface_stcg_rho_ref=1.6,
        surface_stcg_free_shrink=0.40,
        surface_stcg_phi_shrink=0.15,
        surface_stcg_dscore_shrink=0.20,
        surface_stcg_weight_gain=0.35,
        surface_stcg_static_protect=0.80,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.70,
        assoc_hetero_depth_ref_m=2.6,
        assoc_hetero_normal_ref=0.20,
        assoc_hetero_k_inc=0.42,
        assoc_hetero_k_depth=0.10,
        assoc_hetero_k_normal=0.50,
        assoc_hetero_good_cos=0.94,
        assoc_hetero_good_bonus=0.24,
        assoc_hetero_sigma_d_min_scale=0.68,
        assoc_hetero_sigma_d_max_scale=1.60,
        assoc_hetero_sigma_n_min_scale=0.62,
        assoc_hetero_sigma_n_max_scale=1.85,
    ),
    Profile(
        name="dualch_a",
        sigma_n0=0.24,
        dyn_forget_gain=0.02,
        phi=0.76,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.10,
        zc_max_offset=0.05,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.48,
        lzcd_bias_alpha=0.22,
        lzcd_correction_gain=0.42,
        lzcd_max_bias=0.07,
        lzcd_max_step=0.025,
        lzcd_trim_quantile=0.72,
        lzcd_use_geo_channel=True,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.16,
        stcg_conflict_weight=0.65,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.13,
        stcg_free_ratio_ref=0.82,
        stcg_on_thresh=0.58,
        stcg_off_thresh=0.42,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.30,
        surface_stcg_rho_ref=1.65,
        surface_stcg_free_shrink=0.36,
        surface_stcg_phi_shrink=0.14,
        surface_stcg_dscore_shrink=0.18,
        surface_stcg_weight_gain=0.30,
        surface_stcg_static_protect=0.82,
        surface_use_phi_geo_channel=True,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.66,
        assoc_hetero_depth_ref_m=2.2,
        assoc_hetero_normal_ref=0.18,
        assoc_hetero_k_inc=0.56,
        assoc_hetero_k_depth=0.14,
        assoc_hetero_k_normal=0.60,
        assoc_hetero_good_cos=0.92,
        assoc_hetero_good_bonus=0.20,
        assoc_hetero_sigma_d_min_scale=0.70,
        assoc_hetero_sigma_d_max_scale=1.65,
        assoc_hetero_sigma_n_min_scale=0.66,
        assoc_hetero_sigma_n_max_scale=1.95,
    ),
    Profile(
        name="dualch_b",
        sigma_n0=0.22,
        dyn_forget_gain=0.03,
        phi=0.74,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.12,
        zc_max_offset=0.05,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.24,
        lzcd_normal_cos_min=0.50,
        lzcd_bias_alpha=0.24,
        lzcd_correction_gain=0.46,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        lzcd_trim_quantile=0.70,
        lzcd_use_geo_channel=True,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.66,
        stcg_residual_weight=0.22,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.80,
        stcg_on_thresh=0.56,
        stcg_off_thresh=0.40,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.29,
        surface_stcg_rho_ref=1.60,
        surface_stcg_free_shrink=0.40,
        surface_stcg_phi_shrink=0.15,
        surface_stcg_dscore_shrink=0.20,
        surface_stcg_weight_gain=0.34,
        surface_stcg_static_protect=0.80,
        surface_use_phi_geo_channel=True,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.64,
        assoc_hetero_depth_ref_m=2.0,
        assoc_hetero_normal_ref=0.16,
        assoc_hetero_k_inc=0.62,
        assoc_hetero_k_depth=0.18,
        assoc_hetero_k_normal=0.68,
        assoc_hetero_good_cos=0.90,
        assoc_hetero_good_bonus=0.18,
        assoc_hetero_sigma_d_min_scale=0.70,
        assoc_hetero_sigma_d_max_scale=1.65,
        assoc_hetero_sigma_n_min_scale=0.65,
        assoc_hetero_sigma_n_max_scale=2.00,
    ),
    Profile(
        name="dualch_c",
        sigma_n0=0.22,
        dyn_forget_gain=0.04,
        phi=0.72,
        rho=0.00,
        min_weight=0.0,
        max_dscore=1.0,
        max_free_ratio=1e9,
        use_zc=True,
        zc_phi_gate=0.14,
        zc_max_offset=0.05,
        cons_enable=False,
        cons_neighbors=4,
        cons_cos=0.55,
        cons_phi_diff=0.04,
        snef_enable=False,
        snef_block=8,
        snef_qd=0.80,
        snef_md=0.05,
        snef_qf=0.85,
        snef_mf=0.10,
        snef_qphi=1.00,
        snef_mphi=0.00,
        snef_min_keep=16,
        snef_keep_ratio=0.0,
        snef_min_candidates=10,
        snef_anchor_rho_q=0.90,
        snef_anchor_dscore_q=0.25,
        snef_anchor_min=2,
        two_stage_enable=False,
        two_stage_geom_margin=0.0,
        two_stage_dyn_dscore_q=0.70,
        two_stage_dyn_free_q=0.70,
        lzcd_enable=True,
        lzcd_interval=1,
        lzcd_radius_cells=1,
        lzcd_min_neighbors=8,
        lzcd_neighbor_phi_gate=0.22,
        lzcd_normal_cos_min=0.50,
        lzcd_bias_alpha=0.25,
        lzcd_correction_gain=0.48,
        lzcd_max_bias=0.08,
        lzcd_max_step=0.03,
        lzcd_trim_quantile=0.68,
        lzcd_use_geo_channel=True,
        surface_lzcd_apply_in_extraction=True,
        surface_lzcd_bias_scale=1.0,
        stcg_enable=True,
        stcg_alpha=0.18,
        stcg_conflict_weight=0.68,
        stcg_residual_weight=0.20,
        stcg_osc_weight=0.12,
        stcg_free_ratio_ref=0.78,
        stcg_on_thresh=0.56,
        stcg_off_thresh=0.38,
        surface_stcg_enable=True,
        surface_stcg_min_score=0.30,
        surface_stcg_rho_ref=1.55,
        surface_stcg_free_shrink=0.42,
        surface_stcg_phi_shrink=0.16,
        surface_stcg_dscore_shrink=0.21,
        surface_stcg_weight_gain=0.36,
        surface_stcg_static_protect=0.78,
        surface_use_phi_geo_channel=True,
        assoc_hetero_enable=True,
        assoc_hetero_inc_ref_cos=0.70,
        assoc_hetero_depth_ref_m=2.6,
        assoc_hetero_normal_ref=0.20,
        assoc_hetero_k_inc=0.42,
        assoc_hetero_k_depth=0.10,
        assoc_hetero_k_normal=0.50,
        assoc_hetero_good_cos=0.94,
        assoc_hetero_good_bonus=0.24,
        assoc_hetero_sigma_d_min_scale=0.68,
        assoc_hetero_sigma_d_max_scale=1.60,
        assoc_hetero_sigma_n_min_scale=0.62,
        assoc_hetero_sigma_n_max_scale=1.85,
    ),
]


def _run(cmd: List[str], dry_run: bool) -> None:
    print("[cmd]", " ".join(cmd))
    if dry_run:
        return
    subprocess.run(cmd, check=True, cwd=str(PROJECT_ROOT))


def _mean_metric(rec: pd.DataFrame, method: str, key: str) -> float:
    sub = rec[(rec["scene_type"] == "dynamic") & (rec["method"].str.lower() == method)]
    if sub.empty:
        return float("nan")
    vals = pd.to_numeric(sub[key], errors="coerce").to_numpy(dtype=float)
    vals = vals[np.isfinite(vals)]
    if vals.size == 0:
        return float("nan")
    return float(np.mean(vals))


def _load_tables(root: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    candidates = [
        root / "tables",
        root / "oracle" / "tables",
        root / "slam" / "tables",
    ]
    table_dir = None
    for c in candidates:
        if (c / "reconstruction_metrics.csv").exists() and (c / "dynamic_metrics.csv").exists():
            table_dir = c
            break
    if table_dir is None:
        raise FileNotFoundError(f"missing benchmark tables under: {root}")
    rec_p = table_dir / "reconstruction_metrics.csv"
    dyn_p = table_dir / "dynamic_metrics.csv"
    rec = pd.read_csv(rec_p)
    dyn = pd.read_csv(dyn_p)
    rec["method"] = rec["method"].astype(str).str.lower()
    dyn["method"] = dyn["method"].astype(str).str.lower()
    return rec, dyn


def _eval_profile(
    profile: Profile,
    tum_rec: pd.DataFrame,
    tum_dyn: pd.DataFrame,
    bonn_rec: pd.DataFrame,
    bonn_dyn: pd.DataFrame,
    tum_tsdf_ghost: float,
    bonn_tsdf_ghost: float,
) -> Dict[str, float | str | bool]:
    tum_acc_cm = _mean_metric(tum_rec, "egf", "accuracy") * 100.0
    tum_comp_r = _mean_metric(tum_rec, "egf", "recall_5cm") * 100.0
    tum_fscore = _mean_metric(tum_rec, "egf", "fscore")
    tum_ghost = _mean_metric(tum_dyn, "egf", "ghost_ratio")
    tum_red = (tum_tsdf_ghost - tum_ghost) / max(1e-9, tum_tsdf_ghost)

    bonn_acc_cm = _mean_metric(bonn_rec, "egf", "accuracy") * 100.0
    bonn_comp_r = _mean_metric(bonn_rec, "egf", "recall_5cm") * 100.0
    bonn_fscore = _mean_metric(bonn_rec, "egf", "fscore")
    bonn_ghost = _mean_metric(bonn_dyn, "egf", "ghost_ratio")
    bonn_red = (bonn_tsdf_ghost - bonn_ghost) / max(1e-9, bonn_tsdf_ghost)

    pass_tum = bool(tum_acc_cm <= 1.80 and tum_comp_r >= 95.0)
    pass_bonn = bool(bonn_acc_cm <= 2.60 and bonn_comp_r >= 95.0)
    pass_ghost = bool(min(tum_red, bonn_red) >= 0.35)
    passed = bool(pass_tum and pass_bonn and pass_ghost)

    return {
        "profile": profile.name,
        "tum_acc_cm": tum_acc_cm,
        "tum_comp_r_5cm": tum_comp_r,
        "tum_fscore": tum_fscore,
        "tum_ghost_ratio": tum_ghost,
        "tum_ghost_reduction_vs_tsdf": tum_red,
        "bonn_acc_cm": bonn_acc_cm,
        "bonn_comp_r_5cm": bonn_comp_r,
        "bonn_fscore": bonn_fscore,
        "bonn_ghost_ratio": bonn_ghost,
        "bonn_ghost_reduction_vs_tsdf": bonn_red,
        "pass_tum": pass_tum,
        "pass_bonn": pass_bonn,
        "pass_ghost": pass_ghost,
        "pass_all": passed,
    }


def _write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = [
        "profile",
        "tum_acc_cm",
        "tum_comp_r_5cm",
        "tum_fscore",
        "tum_ghost_ratio",
        "tum_ghost_reduction_vs_tsdf",
        "bonn_acc_cm",
        "bonn_comp_r_5cm",
        "bonn_fscore",
        "bonn_ghost_ratio",
        "bonn_ghost_reduction_vs_tsdf",
        "pass_tum",
        "pass_bonn",
        "pass_ghost",
        "pass_all",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=headers)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in headers})


def _write_plot(path: Path, rows: List[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(11.8, 4.8), constrained_layout=True)
    for ax, domain, xk, yk, xthr in [
        (axes[0], "TUM walking (Oracle)", "tum_acc_cm", "tum_comp_r_5cm", 1.80),
        (axes[1], "Bonn all3 (SLAM)", "bonn_acc_cm", "bonn_comp_r_5cm", 2.60),
    ]:
        xs = np.asarray([float(r[xk]) for r in rows], dtype=float)
        ys = np.asarray([float(r[yk]) for r in rows], dtype=float)
        pass_mask = np.asarray([bool(r["pass_all"]) for r in rows], dtype=bool)
        ax.scatter(xs[~pass_mask], ys[~pass_mask], c="#d62728", s=55, label="not pass")
        ax.scatter(xs[pass_mask], ys[pass_mask], c="#2ca02c", s=75, label="pass")
        for r in rows:
            ax.annotate(str(r["profile"]), (float(r[xk]), float(r[yk])), fontsize=8, xytext=(4, 4), textcoords="offset points")
        ax.axvline(xthr, color="#1f77b4", linestyle="--", linewidth=1.0, label=f"Acc <= {xthr:.2f}cm")
        ax.axhline(95.0, color="#9467bd", linestyle="--", linewidth=1.0, label="Comp-R >= 95%")
        ax.set_title(domain)
        ax.set_xlabel("Acc(cm) lower is better")
        ax.set_ylabel("Comp-R(5cm, %) higher is better")
        ax.grid(alpha=0.25)
        ax.set_xlim(left=0.0)
        ax.set_ylim(0.0, 101.0)
    handles, labels = axes[1].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4, frameon=False)
    fig.savefig(path, dpi=220)
    plt.close(fig)


def _score_for_rank(row: Dict[str, object]) -> float:
    # Lower is better. Prefer pass_all first, then lower acc and higher comp-r.
    tum_acc = float(row["tum_acc_cm"])
    bonn_acc = float(row["bonn_acc_cm"])
    tum_comp = float(row["tum_comp_r_5cm"])
    bonn_comp = float(row["bonn_comp_r_5cm"])
    ghost = min(float(row["tum_ghost_reduction_vs_tsdf"]), float(row["bonn_ghost_reduction_vs_tsdf"]))
    penalty = 0.0 if bool(row["pass_all"]) else 1000.0
    return penalty + tum_acc + bonn_acc - 0.02 * (tum_comp + bonn_comp) - 0.5 * ghost


def main() -> None:
    ap = argparse.ArgumentParser(description="P10 precision/completeness profile sweep for local mapping.")
    ap.add_argument("--tum_root", type=str, default="data/tum")
    ap.add_argument("--bonn_root", type=str, default="data/bonn")
    ap.add_argument("--frames", type=int, default=80)
    ap.add_argument("--stride", type=int, default=1)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--voxel_size", type=float, default=0.02)
    ap.add_argument("--max_points_per_frame", type=int, default=3000)
    ap.add_argument("--eval_thresh", type=float, default=0.05)
    ap.add_argument("--out_root", type=str, default="output/post_cleanup/p10_precision_profile")
    ap.add_argument(
        "--summary_csv",
        type=str,
        default="output/summary_tables/local_mapping_precision_profile.csv",
    )
    ap.add_argument(
        "--figure",
        type=str,
        default="assets/acc_comp_tradeoff.png",
    )
    ap.add_argument("--dry_run", action="store_true")
    ap.add_argument("--force", action="store_true")
    ap.add_argument(
        "--profiles",
        type=str,
        default="",
        help="Comma-separated profile names to run. Empty means all.",
    )
    args = ap.parse_args()

    py = sys.executable
    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    selected_profiles = PROFILES
    if args.profiles.strip():
        wanted = {x.strip() for x in args.profiles.split(",") if x.strip()}
        selected_profiles = [p for p in PROFILES if p.name in wanted]
        missing = sorted(wanted.difference({p.name for p in selected_profiles}))
        if missing:
            raise ValueError(f"Unknown profiles: {missing}")
        if not selected_profiles:
            raise ValueError("No profiles selected.")

    rows: List[Dict[str, object]] = []
    tum_tsdf_ghost_ref = math.nan
    bonn_tsdf_ghost_ref = math.nan

    for i, p in enumerate(selected_profiles):
        tag = f"{i:02d}_{p.name}"
        run_dir = out_root / tag
        tum_out = run_dir / "tum_oracle"
        bonn_out = run_dir / "bonn_slam"
        methods = "egf,tsdf" if i == 0 else "egf"
        common_egf = [
            "--egf_sigma_n0",
            str(float(p.sigma_n0)),
            "--egf_assoc_hetero_inc_ref_cos",
            str(float(np.clip(p.assoc_hetero_inc_ref_cos, 1e-3, 1.0))),
            "--egf_assoc_hetero_depth_ref_m",
            str(float(max(1e-3, p.assoc_hetero_depth_ref_m))),
            "--egf_assoc_hetero_normal_ref",
            str(float(max(1e-4, p.assoc_hetero_normal_ref))),
            "--egf_assoc_hetero_k_inc",
            str(float(max(0.0, p.assoc_hetero_k_inc))),
            "--egf_assoc_hetero_k_depth",
            str(float(max(0.0, p.assoc_hetero_k_depth))),
            "--egf_assoc_hetero_k_normal",
            str(float(max(0.0, p.assoc_hetero_k_normal))),
            "--egf_assoc_hetero_good_cos",
            str(float(np.clip(p.assoc_hetero_good_cos, 0.0, 1.0))),
            "--egf_assoc_hetero_good_bonus",
            str(float(np.clip(p.assoc_hetero_good_bonus, 0.0, 0.9))),
            "--egf_assoc_hetero_sigma_d_min_scale",
            str(float(max(1e-3, p.assoc_hetero_sigma_d_min_scale))),
            "--egf_assoc_hetero_sigma_d_max_scale",
            str(float(max(p.assoc_hetero_sigma_d_min_scale, p.assoc_hetero_sigma_d_max_scale))),
            "--egf_assoc_hetero_sigma_n_min_scale",
            str(float(max(1e-3, p.assoc_hetero_sigma_n_min_scale))),
            "--egf_assoc_hetero_sigma_n_max_scale",
            str(float(max(p.assoc_hetero_sigma_n_min_scale, p.assoc_hetero_sigma_n_max_scale))),
            "--egf_truncation",
            "0.08",
            "--egf_dyn_forget_gain",
            str(float(max(0.0, p.dyn_forget_gain))),
            "--egf_lzcd_interval",
            str(int(max(1, p.lzcd_interval))),
            "--egf_lzcd_radius_cells",
            str(int(max(1, p.lzcd_radius_cells))),
            "--egf_lzcd_min_neighbors",
            str(int(max(3, p.lzcd_min_neighbors))),
            "--egf_lzcd_min_phi_w",
            str(float(max(0.0, p.lzcd_min_phi_w))),
            "--egf_lzcd_min_rho",
            str(float(max(0.0, p.lzcd_min_rho))),
            "--egf_lzcd_max_dscore",
            str(float(np.clip(p.lzcd_max_dscore, 0.0, 1.0))),
            "--egf_lzcd_neighbor_phi_gate",
            str(float(max(1e-4, p.lzcd_neighbor_phi_gate))),
            "--egf_lzcd_normal_cos_min",
            str(float(np.clip(p.lzcd_normal_cos_min, 0.0, 1.0))),
            "--egf_lzcd_bias_alpha",
            str(float(np.clip(p.lzcd_bias_alpha, 0.01, 0.95))),
            "--egf_lzcd_correction_gain",
            str(float(np.clip(p.lzcd_correction_gain, 0.0, 1.0))),
            "--egf_lzcd_max_bias",
            str(float(max(1e-4, p.lzcd_max_bias))),
            "--egf_lzcd_max_step",
            str(float(max(1e-4, p.lzcd_max_step))),
            "--egf_lzcd_trim_quantile",
            str(float(np.clip(p.lzcd_trim_quantile, 0.55, 1.0))),
            "--egf_stcg_alpha",
            str(float(np.clip(p.stcg_alpha, 0.01, 0.95))),
            "--egf_stcg_conflict_weight",
            str(float(max(0.0, p.stcg_conflict_weight))),
            "--egf_stcg_residual_weight",
            str(float(max(0.0, p.stcg_residual_weight))),
            "--egf_stcg_osc_weight",
            str(float(max(0.0, p.stcg_osc_weight))),
            "--egf_stcg_free_ratio_ref",
            str(float(max(1e-6, p.stcg_free_ratio_ref))),
            "--egf_stcg_on_thresh",
            str(float(np.clip(p.stcg_on_thresh, 0.05, 0.95))),
            "--egf_stcg_off_thresh",
            str(float(np.clip(p.stcg_off_thresh, 0.01, 0.90))),
            "--egf_raycast_clear_gain",
            "0.0",
            "--egf_surface_phi_thresh",
            str(float(p.phi)),
            "--egf_surface_rho_thresh",
            str(float(p.rho)),
            "--egf_surface_min_weight",
            str(float(p.min_weight)),
            "--egf_surface_max_dscore",
            str(float(p.max_dscore)),
            "--egf_surface_max_free_ratio",
            str(float(p.max_free_ratio)),
            "--egf_surface_use_zero_crossing" if p.use_zc else "--egf_surface_no_zero_crossing",
            "--egf_surface_zero_crossing_max_offset",
            str(float(p.zc_max_offset)),
            "--egf_surface_zero_crossing_phi_gate",
            str(float(p.zc_phi_gate)),
            "--egf_surface_consistency_radius",
            "1",
            "--egf_surface_consistency_min_neighbors",
            str(int(p.cons_neighbors)),
            "--egf_surface_consistency_normal_cos",
            str(float(p.cons_cos)),
            "--egf_surface_consistency_phi_diff",
            str(float(p.cons_phi_diff)),
            "--egf_surface_snef_block_size_cells",
            str(int(p.snef_block)),
            "--egf_surface_snef_dscore_quantile",
            str(float(p.snef_qd)),
            "--egf_surface_snef_dscore_margin",
            str(float(p.snef_md)),
            "--egf_surface_snef_free_ratio_quantile",
            str(float(p.snef_qf)),
            "--egf_surface_snef_free_ratio_margin",
            str(float(p.snef_mf)),
            "--egf_surface_snef_abs_phi_quantile",
            str(float(p.snef_qphi)),
            "--egf_surface_snef_abs_phi_margin",
            str(float(p.snef_mphi)),
            "--egf_surface_snef_min_keep_per_block",
            str(int(p.snef_min_keep)),
            "--egf_surface_snef_min_keep_ratio_per_block",
            str(float(np.clip(p.snef_keep_ratio, 0.0, 1.0))),
            "--egf_surface_snef_min_candidates_per_block",
            str(int(p.snef_min_candidates)),
            "--egf_surface_snef_anchor_rho_quantile",
            str(float(np.clip(p.snef_anchor_rho_q, 0.0, 1.0))),
            "--egf_surface_snef_anchor_dscore_quantile",
            str(float(np.clip(p.snef_anchor_dscore_q, 0.0, 1.0))),
            "--egf_surface_snef_anchor_min_per_block",
            str(int(max(0, p.snef_anchor_min))),
            "--egf_surface_two_stage_geom_margin",
            str(float(max(0.0, p.two_stage_geom_margin))),
            "--egf_surface_two_stage_dynamic_dscore_quantile",
            str(float(np.clip(p.two_stage_dyn_dscore_q, 0.0, 1.0))),
            "--egf_surface_two_stage_dynamic_free_quantile",
            str(float(np.clip(p.two_stage_dyn_free_q, 0.0, 1.0))),
            "--egf_surface_two_stage_dynamic_rho_quantile",
            str(float(np.clip(p.two_stage_dyn_rho_q, 0.0, 1.0))),
            "--egf_surface_two_stage_dynamic_rho_margin",
            str(float(max(0.0, p.two_stage_dyn_rho_margin))),
            "--egf_surface_lzcd_bias_scale",
            str(float(max(0.0, p.surface_lzcd_bias_scale))),
            "--egf_surface_stcg_min_score",
            str(float(np.clip(p.surface_stcg_min_score, 0.0, 1.0))),
            "--egf_surface_stcg_rho_ref",
            str(float(max(1e-6, p.surface_stcg_rho_ref))),
            "--egf_surface_stcg_free_shrink",
            str(float(np.clip(p.surface_stcg_free_shrink, 0.0, 1.0))),
            "--egf_surface_stcg_phi_shrink",
            str(float(np.clip(p.surface_stcg_phi_shrink, 0.0, 1.0))),
            "--egf_surface_stcg_dscore_shrink",
            str(float(np.clip(p.surface_stcg_dscore_shrink, 0.0, 1.0))),
            "--egf_surface_stcg_weight_gain",
            str(float(max(0.0, p.surface_stcg_weight_gain))),
            "--egf_surface_stcg_static_protect",
            str(float(np.clip(p.surface_stcg_static_protect, 0.0, 1.0))),
            "--egf_surface_adaptive_enable",
        ]
        if p.lzcd_enable:
            common_egf.append("--egf_lzcd_enable")
        if p.lzcd_use_geo_channel:
            common_egf.append("--egf_lzcd_use_geo_channel")
        else:
            common_egf.append("--egf_lzcd_no_geo_channel")
        if p.stcg_enable:
            common_egf.append("--egf_stcg_enable")
        if p.assoc_hetero_enable:
            common_egf.append("--egf_assoc_hetero_enable")
        if p.cons_enable:
            common_egf.append("--egf_surface_consistency_enable")
        if p.snef_enable:
            common_egf.append("--egf_surface_snef_local_enable")
        if p.two_stage_enable:
            common_egf.append("--egf_surface_two_stage_enable")
        if p.surface_lzcd_apply_in_extraction:
            common_egf.append("--egf_surface_lzcd_apply_in_extraction")
        if p.surface_stcg_enable:
            common_egf.append("--egf_surface_stcg_enable")
        if p.surface_use_phi_geo_channel:
            common_egf.append("--egf_surface_use_phi_geo_channel")
        else:
            common_egf.append("--egf_surface_no_phi_geo_channel")
        if p.two_stage_dyn_require_low_rho:
            common_egf.append("--egf_surface_two_stage_dynamic_require_low_rho")
        else:
            common_egf.append("--egf_surface_two_stage_dynamic_no_require_low_rho")

        tum_cmd = [
            py,
            "scripts/run_benchmark.py",
            "--dataset_kind",
            "tum",
            "--dataset_root",
            str(args.tum_root),
            "--protocol",
            "oracle",
            "--static_sequences",
            "",
            "--dynamic_sequences",
            "rgbd_dataset_freiburg3_walking_xyz,rgbd_dataset_freiburg3_walking_static,rgbd_dataset_freiburg3_walking_halfsphere",
            "--methods",
            methods,
            "--frames",
            str(int(args.frames)),
            "--stride",
            str(int(args.stride)),
            "--seed",
            str(int(args.seed)),
            "--voxel_size",
            str(float(args.voxel_size)),
            "--max_points_per_frame",
            str(int(args.max_points_per_frame)),
            "--eval_thresh",
            str(float(args.eval_thresh)),
            "--out_root",
            str(tum_out),
            *common_egf,
        ]
        if args.force:
            tum_cmd.append("--force")
        _run(tum_cmd, args.dry_run)

        bonn_cmd = [
            py,
            "scripts/run_benchmark.py",
            "--dataset_kind",
            "bonn",
            "--dataset_root",
            str(args.bonn_root),
            "--protocol",
            "slam",
            "--bonn_dynamic_preset",
            "all3",
            "--static_sequences",
            "",
            "--methods",
            methods,
            "--frames",
            str(int(args.frames)),
            "--stride",
            str(int(args.stride)),
            "--seed",
            str(int(args.seed)),
            "--voxel_size",
            str(float(args.voxel_size)),
            "--max_points_per_frame",
            str(int(args.max_points_per_frame)),
            "--eval_thresh",
            str(float(args.eval_thresh)),
            "--out_root",
            str(bonn_out),
            *common_egf,
        ]
        if args.force:
            bonn_cmd.append("--force")
        _run(bonn_cmd, args.dry_run)

        if args.dry_run:
            continue

        tum_rec, tum_dyn = _load_tables(tum_out)
        bonn_rec, bonn_dyn = _load_tables(bonn_out)
        if i == 0:
            tum_tsdf_ghost_ref = _mean_metric(tum_dyn, "tsdf", "ghost_ratio")
            bonn_tsdf_ghost_ref = _mean_metric(bonn_dyn, "tsdf", "ghost_ratio")
        if not np.isfinite(tum_tsdf_ghost_ref) or not np.isfinite(bonn_tsdf_ghost_ref):
            raise RuntimeError("TSDF reference ghost metrics are missing in baseline profile.")
        row = _eval_profile(
            profile=p,
            tum_rec=tum_rec,
            tum_dyn=tum_dyn,
            bonn_rec=bonn_rec,
            bonn_dyn=bonn_dyn,
            tum_tsdf_ghost=tum_tsdf_ghost_ref,
            bonn_tsdf_ghost=bonn_tsdf_ghost_ref,
        )
        row["out_dir"] = str(run_dir)
        rows.append(row)
        print(
            "[profile]"
            f" {p.name}"
            f" tum_acc={row['tum_acc_cm']:.3f} tum_compR={row['tum_comp_r_5cm']:.2f}"
            f" bonn_acc={row['bonn_acc_cm']:.3f} bonn_compR={row['bonn_comp_r_5cm']:.2f}"
            f" ghost_red_min={min(float(row['tum_ghost_reduction_vs_tsdf']), float(row['bonn_ghost_reduction_vs_tsdf'])):.3f}"
            f" pass={bool(row['pass_all'])}"
        )

    if args.dry_run:
        return
    if not rows:
        raise RuntimeError("No profile results were produced.")

    rows_sorted = sorted(rows, key=_score_for_rank)
    best = rows_sorted[0]

    _write_csv(Path(args.summary_csv), rows_sorted)
    _write_plot(Path(args.figure), rows_sorted)
    best_json = Path(args.out_root) / "best_profile.json"
    best_json.write_text(json.dumps(best, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[done] summary: {args.summary_csv}")
    print(f"[done] figure: {args.figure}")
    print(f"[done] best profile: {best_json}")
    print(f"[best] {json.dumps(best, ensure_ascii=False)}")


if __name__ == "__main__":
    main()
